!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  Kd: 0.001
  Kd_scale: 0.1
  Ki: 0.19
  Ki_scale: 10.0
  Kp: 0.05
  Kp_scale: 1.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      Kd: 0.001
      Kd_scale: 0.1
      Ki: 0.19
      Ki_scale: 10.0
      Kp: 0.05
      Kp_scale: 1.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
state: []
